default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: whore_catcher

production:
  <<: *default
  database: whore_catcher

test:
  <<: *default
  database: whore_catcher
