
$(document).ready ->
  min_rand = 18
  max_rand = 632
  counter = 0
  counter_whore = 0
  lives = 3
  whore_animate = undefined
  right_direction = true
  total_time = 0

  whore_builder = ->
    setTimeout (->
      $whore = $('<div class="whore"></div>')
      $whore.fadeIn('slow').prependTo '.wrapper'
      $whore.css 'left', Math.floor(Math.random() * 600)
      counter_whore += 1
      return
    ), Math.floor(Math.random() * 2000)
    return

  intersects = (a, b) ->
    x1 = a.offset().left
    y1 = a.offset().top
    h1 = a.outerHeight(true) - 18
    w1 = a.outerWidth(true)
    b1 = y1 + h1
    r1 = x1 + w1
    x2 = b.offset().left
    y2 = b.offset().top
    h2 = b.outerHeight(true)
    w2 = b.outerWidth(true)
    b2 = y2 + h2
    r2 = x2 + w2
    if b1 < y2 or y1 > b2 or r1 < x2 or x1 > r2
      return false
    true

  whore_animation = ->
    console.log 'whore_animation'
    window.timerId = setInterval((->
      total_time += 50
      if lives < 1
        console.log '====== temer ====>>>'
        clearInterval window.timerId
        console.log '==========>>>'
        console.log window.timerId

        $.ajax
          method: 'POST'
          dataType: "json"
          url: "/scores"
          data: { score: { total_time: total_time, whore_count: counter }}
          success: (response) =>
            $('.whore').remove()
            $('.wrapper').addClass('finish-wrapper').slideDown 'slow'
            $('.total_time').html 'Время игры: ' + total_time / 1000
            console.log counter
            $('.total_whore').html 'ШЛЮХ: ' + counter
            console.log '=-=-==>>>>>>'
            console.log timerId
            $.getJSON '/scores', (data) =>
              $.each data, (i, score) ->
                $('.scores').append("<li>#{++i})<b>#{score.whore_count}</b> -#{score.user.name} (#{score.total_time / 1000})</li>")

              false

      $.each $('.whore'), (i, whore) ->
        $whore = $(whore)
        $whore.animate { 'top': '+=5px' }, 50
        cross = intersects($whore, $('.catcher'))
        if cross == true
          $('body').append '<audio src="audio/coinsound.mp3" autoplay ></audio>'
          counter += 1
          $('.whore-counter').html 'ШЛЮХ: ' + counter
          $whore.remove()
          whore_builder()
          if counter / counter_whore > 0.8
            whore_builder()
        else if $whore.position().top > 400
          lives -= 1
          $('.live-counter span').text 'x ' + lives
          $whore.remove()
          whore_builder()
    ), 50)
    console.log '!!! timerId !!!!'
    console.log  window.timerId
    console.log '!!! timerId !!!!'

    return

  $('.start_button').click ->
    $('.headpiece').remove()
    console.log $('audio').attr('src')
    $('audio').attr 'src', 'audio/bit.mp3'
    whore_builder()
    window.whore_builder = whore_builder
    whore_animation()
    return

  $('body').keypress (e) ->
    if e.keyCode == 97
      console.log 'Left button'
      $('.catcher').removeClass('right-direction').addClass 'left-direction'
      $('.catcher-head').removeClass('right-direction').addClass 'left-direction'
      $('.catcher-basket').removeClass('right-direction').addClass 'left-direction'
      if right_direction == true
        $('.catcher-head').css 'left', '+=100px'
        $('.catcher-basket').css 'left', '+=100px'
      right_direction = false
      if $('.catcher').position().left >= '10'
        $('.catcher').css 'left', '-=20px'
        $('.catcher-head').css 'left', '-=20px'
        $('.catcher-basket').css 'left', '-=20px'
    else if e.keyCode == 100
      console.log 'Right button'
      $('.catcher').removeClass('left-direction').addClass 'right-direction'
      $('.catcher-head').removeClass('left-direction').addClass 'right-direction'
      $('.catcher-basket').removeClass('left-direction').addClass 'right-direction'
      if right_direction == false
        $('.catcher-head').css 'left', '-=100px'
        $('.catcher-basket').css 'left', '-=100px'
      right_direction = true
      if $('.catcher').position().left <= '555'
        $('.catcher').css 'left', '+=20px'
        $('.catcher-head').css 'left', '+=20px'
        $('.catcher-basket').css 'left', '+=20px'
    # var cross1 = intersects($( ".whore" ), $('.catcher'));
    # console.log(cross1);
    return
  return

# ---
# generated by js2coffee 2.1.0